services:
  postgres:
    image: postgres:16
    container_name: bookdb
    environment:
      POSTGRES_USER: bookuser
      POSTGRES_PASSWORD: bookpass
      POSTGRES_DB: bookdb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: book-catalog
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/bookdb
      DATABASE_USER: bookuser
      DATABASE_PASSWORD: bookpass