server:
  applicationConnectors:
    - type: http
      #port: 8080
      port: ${PORT:-8080}
  adminConnectors:
    - type: http
      #port: 8081
      port: ${PORT:-8080} # Use same port on Render

logging:
  level: INFO
  loggers:
    org.example: DEBUG

database:
  driverClass: org.postgresql.Driver
  user: ${DATABASE_USER:-bookuser}
  password: ${DATABASE_PASSWORD:-bookpass}
  # This is the fallback when running locally, when deploying to the cloud, Render will set the DATABASE_URL
  url: ${DATABASE_URL:-jdbc:postgresql://postgres:5432/bookdb}
  validationQuery: "SELECT 1"
