{
 "title": "Book Service Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(io_dropwizard_jetty_MutableServletContextHandler_2xx_responses_total{job=\"book-service\"}[5m])",
     "legendFormat": "2xx Success"
    },
    {
     "expr": "rate(io_dropwizard_jetty_MutableServletContextHandler_4xx_responses_total{job=\"book-service\"}[5m])",
     "legendFormat": "4xx Client Errors"
    },
    {
     "expr": "rate(io_dropwizard_jetty_MutableServletContextHandler_5xx_responses_total{job=\"book-service\"}[5m])",
     "legendFormat": "5xx Server Errors"
    }
   ]
  },
  {
   "title": "Error Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "io_dropwizard_jetty_MutableServletContextHandler_percent_4xx_1m{job=\"book-service\"} * 100",
     "legendFormat": "4xx Error Rates Pct"
    },
    {
     "expr": "io_dropwizard_jetty_MutableServletContextHandler_percent_5xx_1m{job=\"book-service\"} * 100",
     "legendFormat": "5xx Error Rate Pct"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "io_dropwizard_jetty_MutableServletContextHandler_get_requests{job=\"book-service\", quantile=\"0.95\"}",
     "legendFormat": "GET Request"
    },
    {
     "expr": "io_dropwizard_jetty_MutableServletContextHandler_post_requests{job=\"book-service\", quantile=\"0.95\"}",
     "legendFormat": "POST Request"
    }
   ]
  },
  {
   "title": "Heap Memeory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(jvm_memory_heap_used{job=\"book-service\"} / jvm_memory_heap_max{job=\"book-service\"}) * 100",
     "legendFormat": "Pct Used"
    }
   ]
  },
  {
   "title": "Response Time by Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "io_dropwizard_jetty_MutableServletContextHandler_requests{job=\"book-service\", quantile=\"0.5\"}",
     "legendFormat": "p5"
    },
    {
     "expr": "io_dropwizard_jetty_MutableServletContextHandler_requests{job=\"book-service\", quantile=\"0.95\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "io_dropwizard_jetty_MutableServletContextHandler_requests{job=\"book-service\", quantile=\"0.99\"}",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(io_dropwizard_jetty_MutableServletContextHandler_requests_count{job=\"book-service\"}[1m])",
     "legendFormat": "Request per sec"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "io_dropwizard_jetty_MutableServletContextHandler_active_requests{job=\"book-service\"}",
     "legendFormat": "Requests"
    }
   ]
  }
 ]
}